config/routes.rb
RailsApp::Application.routes.draw do
  resources :pueblos

end

app/models/pueblo.rb
class Pueblo < ActiveRecord::Base
  mount_uploader :song, MusicPuebloUploader
  attr_accessible :ciudad, :descFiesta, :descripcion, :estado, :gastronomia, :latitude, :longitude, :lugaresInt, :mesFiesta, :image ,:song, :song_cache, :video
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pueblos_controller.rb
class PueblosController < ApplicationController
  # GET /pueblos
  # GET /pueblos.json
  def index


    @ciudads = Pueblo.all
    if(@ciudads)
      @last_modified = Pueblo.order("updated_at").last
      @last_update =@last_modified.updated_at 
    else
      @last_update=DateTime.now.to_date
    end
   #:ciudad, :descFiesta, :descripcion, :estado, :gastronomia, :latitude, :longitude, :lugaresInt, :mesFiesta, :image ,:song, :song_cache
    @ciudads_ = @ciudads.map do |u|
      { :Ciudad => u.ciudad , :Estado => u.estado, :Latitude => u.latitude, :Longitude => u.longitude, :Imagen => u.image, :Descripcion => u.descripcion ,:DescripcionFiesta =>u.descFiesta, :LugaresInteres =>u.lugaresInt, :MesFiesta => u.mesFiesta, :Gastronomia => u.gastronomia, :Song => u.song.url, :Video => u.video}
    end
    @cool_json ={:Title=>"Pueblos Magicos",:LastUpdate=> @last_update, :Ciudades=>@ciudads_ }.to_json
#json = { :users => @userlist, :contacts => current_user.contacts }.to_json
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cool_json }
    end








    #@pueblos = Pueblo.all

    #respond_to do |format|
    #  format.html # index.html.erb
    #  format.json { render json: @pueblos }
    #end
  end

  # GET /pueblos/1
  # GET /pueblos/1.json
  def show
    @pueblo = Pueblo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pueblo }
    end
  end

  # GET /pueblos/new
  # GET /pueblos/new.json
  def new
    @pueblo = Pueblo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pueblo }
    end
  end

  # GET /pueblos/1/edit
  def edit
    @pueblo = Pueblo.find(params[:id])
  end

  # POST /pueblos
  # POST /pueblos.json
  def create
    @pueblo = Pueblo.new(params[:pueblo])

    respond_to do |format|
      if @pueblo.save
        format.html { redirect_to @pueblo, notice: 'Pueblo was successfully created.' }
        format.json { render json: @pueblo, status: :created, location: @pueblo }
      else
        format.html { render action: "new" }
        format.json { render json: @pueblo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pueblos/1
  # PUT /pueblos/1.json
  def update
    @pueblo = Pueblo.find(params[:id])

    respond_to do |format|
      if @pueblo.update_attributes(params[:pueblo])
        format.html { redirect_to @pueblo, notice: 'Pueblo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pueblo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pueblos/1
  # DELETE /pueblos/1.json
  def destroy
    @pueblo = Pueblo.find(params[:id])
    @pueblo.destroy

    respond_to do |format|
      format.html { redirect_to pueblos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pueblos_helper.rb
module PueblosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pueblos/_form.html.erb
<%= form_for @pueblo, :html => {:multipart => true} do |f| %>
  <% if @pueblo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pueblo.errors.count, "error") %> prohibited this pueblo from being saved:</h2>

      <ul>
      <% @pueblo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ciudad %><br />
    <%= f.text_field :ciudad %>
  </div>
  <div class="field">
    <%= f.label :estado %><br />
    <%= f.text_field :estado %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br />
    <%= f.text_area :descripcion %>
  </div>
  <div class="field">
    <%= f.label :mesFiesta %><br />
    <%= f.text_field :mesFiesta %>
  </div>
  <div class="field">
    <%= f.label :lugaresInt %><br />
    <%= f.text_area :lugaresInt %>
  </div>
  <div class="field">
    <%= f.label :descFiesta %><br />
    <%= f.text_area :descFiesta %>
  </div>
  <div class="field">
    <%= f.label :gastronomia %><br />
    <%= f.text_area :gastronomia %>
  </div>
  <div class="field">
    <%= f.label :video %><br />
    <%= f.text_area :video %>
  </div>
  <div class="field">
    <%= f.file_field :song %>
    <%= f.hidden_field :song_cache %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pueblos/edit.html.erb
<h1>Editing pueblo</h1>

<%= render 'form' %>

<%= link_to 'Show', @pueblo %> |
<%= link_to 'Back', pueblos_path %>

app/views/pueblos/index.html.erb
<h1>Listing pueblos</h1>

<table>
  <tr>
    <th>Ciudad</th>
    <th>Estado</th>
    <th>Image</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th>Descripcion</th>
    <th>Mesfiesta</th>
    <th>Lugaresint</th>
    <th>Descfiesta</th>
    <th>Gastronomia</th>
    <th>Song</th>
    <th>Video</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ciudads.each do |pueblo| %>
  <tr>
    <td><%= pueblo.ciudad %></td>
    <td><%= pueblo.estado %></td>
    <td><%= pueblo.image %></td>
    <td><%= pueblo.latitude %></td>
    <td><%= pueblo.longitude %></td>
    <td><%= pueblo.descripcion %></td>
    <td><%= pueblo.mesFiesta %></td>
    <td><%= pueblo.lugaresInt %></td>
    <td><%= pueblo.descFiesta %></td>
    <td><%= pueblo.gastronomia %></td>
    <td><%= pueblo.song.url %></td>
    <td><%= pueblo.video %></td>
    <td><%= link_to 'Show', pueblo %></td>
    <td><%= link_to 'Edit', edit_pueblo_path(pueblo) %></td>
    <td><%= link_to 'Destroy', pueblo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pueblo', new_pueblo_path %>

app/views/pueblos/new.html.erb
<h1>New pueblo</h1>

<%= render 'form' %>

<%= link_to 'Back', pueblos_path %>

app/views/pueblos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Ciudad:</b>
  <%= @pueblo.ciudad %>
</p>

<p>
  <b>Estado:</b>
  <%= @pueblo.estado %>
</p>

<p>
  <b>Image:</b>
  <%= @pueblo.image %>
</p>

<p>
  <b>Latitude:</b>
  <%= @pueblo.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @pueblo.longitude %>
</p>

<p>
  <b>Descripcion:</b>
  <%= @pueblo.descripcion %>
</p>

<p>
  <b>Mesfiesta:</b>
  <%= @pueblo.mesFiesta %>
</p>

<p>
  <b>Lugaresint:</b>
  <%= @pueblo.lugaresInt %>
</p>

<p>
  <b>Descfiesta:</b>
  <%= @pueblo.descFiesta %>
</p>

<p>
  <b>Gastronomia:</b>
  <%= @pueblo.gastronomia %>
</p>
<p>
  <b>Video:</b>
  <%= @pueblo.video %>
</p>
<p>
  <b>Song:</b>
  <%= @pueblo.song.url %>

</p>
<%= link_to 'Edit', edit_pueblo_path(@pueblo) %> |
<%= link_to 'Back', pueblos_path %>